const ADD_TODO = 'ADD_TODO';
const DELETE_TODO = 'DELETE_TODO';
const EDIT_TODO = 'EDIT_TODO';
const COMPLETE_TODO = 'COMPLETE_TODO';
const COMPLETE_ALL = 'COMPLETE_ALL';
const CLEAR_COMPLETED = 'CLEAR_COMPLETED';

const FIND_TUTORIAL = 'FIND_TUT';
const ADD_TUTORIAL = 'ADD_TUT';
const DELETE_TUTORIAL = 'DELETE_TUT';
const EDIT_TUTORIAL = 'EDIT_TUT';
